Mishal filter diaries
freshbitsweb/website pull request #12
Opened 2022-03-26 12:02 UTC by misusonu18

# added the filter
## video file

https://user-images.githubusercontent.com/52093984/160238447-7b615529-c0bd-4a03-bf2a-919dd73811d9.mp4

2022-03-28 11:20 UTC, hirenkeraliya requested changes

2022-03-28 11:20 UTC, hirenkeraliya commented on diaries.html
> +                    <a class="btn pink" onclick="displayFilterSelection('fun')">
```diff
-displayFilterSelection('fun')
+displayActivityFor('fun')
```

2022-03-28 11:20 UTC, hirenkeraliya commented on diaries.html
> +    <script type="text/javascript" src="js/data.js"></script>
`diaries-data.js`

2022-03-28 11:20 UTC, hirenkeraliya commented on diaries.html
> +        }
code is not needed. I think it's bad to call 2 listeners for the click-on button.

2022-03-28 11:20 UTC, hirenkeraliya commented on js/custom_script.js
> +        else if (filterName === 'all') {
```javascript
if (condition) {
    
} else if(condition) {
    
}
```

A conditional statement can be written like this.

2022-03-28 11:20 UTC, hirenkeraliya commented on js/custom_script.js
> +            dairyData.images.forEach((image) => {
make some spacing divide code if needed.

2022-03-28 11:20 UTC, hirenkeraliya commented on js/custom_script.js
> +displayFilterSelection();
always all the files have a newline at end of the file.

2022-03-30 14:34 UTC, gauravmak requested changes

2022-03-30 14:34 UTC, gauravmak commented on js/custom_script.js
> +        if (dairyData.tag === filterName) {
Same code being repeated in else if

2022-03-30 14:44 UTC, merged